id: P817DA7FA
initial_creation_type: ocr
source_metadata:
  volumes:
    0d9644a9d124423c99c3d8b08cabbcce:
      base_file: v114.txt
      image_group_id: I1PD95959
      title: ཤེས་རབ་བརྒྱ་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1872
      volume_number: 114
